collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.349624
  brandStrength: 0.400383518775925
  lightness: 0.5214823
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  rhythmicContrast: 0.2798066
typography_spectrum: 0.452739
layout_spectrum: 0.4914071
name: Storybook Lady Charitable Foundation
